// Code generated by mockery v2.33.2. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// HTTPServer is an autogenerated mock type for the HTTPServer type
type HTTPServer struct {
	mock.Mock
}

// Start provides a mock function with given fields: port
func (_m *HTTPServer) Start(port string) error {
	ret := _m.Called(port)

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(port)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewHTTPServer creates a new instance of HTTPServer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewHTTPServer(t interface {
	mock.TestingT
	Cleanup(func())
}) *HTTPServer {
	mock := &HTTPServer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
