name: Linter

on:
  pull_request:
    branches:
      - main
      - develop
      - staging

jobs:
  golangci-lint:
    name: runner / golangci-lint
    runs-on: ubuntu-latest

    steps:
      - name: Fetch Repository
        uses: actions/checkout@v3

      - name: Run Golint
        uses: reviewdog/action-golangci-lint@v2