name: Security

on:
  pull_request:
    branches:
      - main
      - develop
      - staging

jobs:
  Gosec:
    runs-on: ubuntu-latest

    steps:
      - name: Fetch Repository
        uses: actions/checkout@v3

      - name: Run Gosec
        uses: securego/gosec@master
        with:
          args: ./...